# Generated by Django 5.0.6 on 2024-05-13 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_region', models.CharField(max_length=300)),
                ('school_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=300)),
                ('group_teacher', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to=settings.AUTH_USER_MODEL)),
                ('group_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.school')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_fullname', models.CharField(max_length=300)),
                ('pupil_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.groups')),
                ('pupil_username', models.ForeignKey(limit_choices_to={'is_user': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
