# Generated by Django 5.0.6 on 2024-05-13 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_pupils_pupil_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_teacher',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pupils',
            name='pupil_username',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
