# Generated by Django 5.0.6 on 2024-05-13 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_groups_group_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupils',
            name='pupil_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.groups'),
        ),
    ]
